#!/bin/sh

set -e

case "$1" in
    upgrade|deconfigure)
    ;;

    remove|purge)
        rm /etc/skel/.config/autostart/slimbook-client-autostart.desktop
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
